-- SADECE MEVCUT SUPABASE PROJESİNE UYGULANACAK FARKLAR
-- Supabase > SQL Editor içinde bir kez çalıştırabilirsiniz.

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  name text not null check (length(trim(name)) between 1 and 50),
  rating smallint not null check (rating between 1 and 5),
  comment text not null check (length(trim(comment)) between 1 and 500),
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  title text not null check (length(trim(title)) between 1 and 120),
  message text not null check (length(trim(message)) between 1 and 1000),
  active boolean not null default true,
  start_date date,
  end_date date,
  created_at timestamptz not null default now(),
  constraint notifications_date_range check (
    start_date is null or end_date is null or end_date >= start_date
  )
);

alter table public.reviews enable row level security;
alter table public.notifications enable row level security;

drop policy if exists "Public read reviews" on public.reviews;
drop policy if exists "Public insert reviews" on public.reviews;
drop policy if exists "Admins delete reviews" on public.reviews;

create policy "Public read reviews"
on public.reviews for select to anon, authenticated
using (true);

create policy "Public insert reviews"
on public.reviews for insert to anon, authenticated
with check (
  length(trim(name)) between 1 and 50
  and rating between 1 and 5
  and length(trim(comment)) between 1 and 500
);

create policy "Admins delete reviews"
on public.reviews for delete to authenticated
using (public.is_admin());

drop policy if exists "Public read active notifications" on public.notifications;
drop policy if exists "Admins read notifications" on public.notifications;
drop policy if exists "Admins insert notifications" on public.notifications;
drop policy if exists "Admins update notifications" on public.notifications;
drop policy if exists "Admins delete notifications" on public.notifications;

-- Müşteri: aktif, süresi geçmemiş ve başlangıcı en fazla 3 gün sonra olan bildirimleri görür.
create policy "Public read active notifications"
on public.notifications for select to anon, authenticated
using (
  active = true
  and (start_date is null or start_date <= current_date + 3)
  and (end_date is null or end_date >= current_date)
);

create policy "Admins read notifications"
on public.notifications for select to authenticated
using (public.is_admin());

create policy "Admins insert notifications"
on public.notifications for insert to authenticated
with check (public.is_admin());

create policy "Admins update notifications"
on public.notifications for update to authenticated
using (public.is_admin()) with check (public.is_admin());

create policy "Admins delete notifications"
on public.notifications for delete to authenticated
using (public.is_admin());

grant select, insert on public.reviews to anon, authenticated;
grant delete on public.reviews to authenticated;
grant usage, select on sequence public.reviews_id_seq to anon, authenticated;

grant select on public.notifications to anon, authenticated;
grant insert, update, delete on public.notifications to authenticated;
grant usage, select on sequence public.notifications_id_seq to authenticated;

alter table public.notifications replica identity full;
alter table public.reviews replica identity full;

do $$
begin
  if exists (select 1 from pg_publication where pubname='supabase_realtime') then
    if not exists (
      select 1 from pg_publication_tables
      where pubname='supabase_realtime' and schemaname='public' and tablename='notifications'
    ) then
      alter publication supabase_realtime add table public.notifications;
    end if;

    if not exists (
      select 1 from pg_publication_tables
      where pubname='supabase_realtime' and schemaname='public' and tablename='reviews'
    ) then
      alter publication supabase_realtime add table public.reviews;
    end if;
  end if;
end $$;
